### ISSUE TITLE
O2KR5 - Dashboards on headcount/costs/budget/hiring

### ISSUE THREAD

**Issue by ceripower** [status-im/people-ops#10]
Provide detailed dashboard per team/swarm with information on budgets/costs/progress. 

Moar transparency?

**Comment by rajanie** [comment]
this might be cheesey, but would something like a bi-monthly newsletter via email be cool?

**Comment by ceripower** [comment]
> this might be cheesey, but would something like a bi-monthly newsletter via email be cool?

I think that's cool - something like connecting people across Status through curating stories and updates?

**Comment by rajanie** [comment]
I actually forgot about discuss, could also be a blog post there. But it would be a way to keep people updated

**Comment by ceripower** [comment]
From the 190107 TH:

> Organizational health metrics. For example:
>Developer contributions
>e.g. # of contributors, retention rates, top committers, PRs/day, binary release events
>Financial
>e.g. SNT/BTC, SNT/ETH, burn rate, revenue, etc.
>Network health
>e.g. Status Node live, %-uptime, daily transacting users

**Comment by ceripower** [comment]
> this might be cheesey, but would something like a bi-monthly newsletter via email be cool?

@rajanie it looks like [this work](https://discuss.status.im/t/transparency-swarm-updates/951) being done by Marketing handles written updates pretty thoroughly already, so it looks to me like a newsletter at this stage has been covered, wdyt?

**Comment by ceripower** [comment]
> Financial
> e.g. SNT/BTC, SNT/ETH, burn rate, revenue, etc.

@DanBigM - is the burn rate and revenue something you could provide monthly? we could incorporate it into an overall dashboard along with people info

**Comment by ceripower** [comment]
Info from Jakub on network health:

[Peer/client count](https://grafana.status.im/d/wV77E-4mz/statusd-metrics?panelId=18&fullscreen&orgId=1&from=now-90d&to=now)
[Whisper envelopes](https://grafana.status.im/d/wV77E-4mz/statusd-metrics?panelId=3&fullscreen&orgId=1&from=now-90d&to=now)

**Comment by ceripower** [comment]
> this might be cheesey, but would something like a bi-monthly newsletter via email be cool?

Always nice to see a plan worked out 🙌🏻

**Comment by rajanie** [comment]
hahaha i'm glad we went with weekly :D

**Comment by ceripower** [comment]
Closing this out for Q1 2019. OKR partially met inasmuch as we are reporting weekly on people/finance news in the newsletter.

As per @jonathanbarker suggestion:

> I think we could close this OKR out as met, and then define a slightly different Q2 goal based on launching live budget updates, or something more specific to budget/finance/hiring

Agree ^
