### ISSUE TITLE
O5KR3 Transparency on People Ops work

### ISSUE THREAD

**Issue by ceripower** [status-im/people-ops#11]
Add weekly meeting notes to notes.status.im

**Comment by rajanie** [comment]
started updating People site: https://notes.status.im/ntGt2rE6RA6_twYa2H1pxg?both

**Comment by ceripower** [comment]
Awesome, thanks Rajanie!

**Comment by ceripower** [comment]
To make this a bit more measurable, defining what `transparency` constitutes:

- Adding notes of weekly People Ops hangouts to our team page
- Posting retrospective on each quarter to Discuss
- Daily standups (in the team channel) - should we copy these across into our team page somewhere or is it fine for these to be limited to POps only?
- Sharing information on hiring and finance (via newsletter, but needs more work in Q2 OKR)

Anything else? Otherwise I think we can consider this OKR complete based on the above ^.
