### ISSUE TITLE
O1KR5 - Update People Ops site for GmbH 2.0

### ISSUE THREAD

**Issue by ceripower** [status-im/people-ops#12]
Our People Ops site is ridiculously out of date

**Comment by ceripower** [comment]
Fixed broken links: https://people-ops.status.im/welcome/

**Comment by rajanie** [comment]
We should update this page: people-ops.status.im/managing-slack/ since we no longer use slack. or change the name to "Managing **status chat"**

**Comment by ceripower** [comment]
Added a step by step `what to do on your first day` guide to this page, it was a bit sparse: https://people-ops.status.im/your-first-day/

**Comment by rajanie** [comment]
updated https://people-ops.status.im/laptop-and-phone/

**Comment by ceripower** [comment]
Also team https://people-ops.status.im/tag/team page needs updating

**Comment by ceripower** [comment]
@rajanie am thinking about changing the wording in https://people-ops.status.im/laptop-and-phone/ to make phones more for cases of where there's a business need versus everyone can buy one / needs team lead approval, wdyt?

**Comment by rajanie** [comment]
Agreed! I think we should change it. We should also add getting approval for devices so we can send out loaners when we have them, rather than people just buying devices.

**Comment by ceripower** [comment]
Sounds good, gave it a whirl. How about this https://people-ops.status.im/laptop-and-phone/ @rajanie ?

**Comment by rajanie** [comment]
Should we remove "Your devices can be replaced for new ones after 24-36 months"? That could create unnecessary device upgrades. 
Maybe change the the wording to something "Around 36 months, ping PeopleOps, if your device needs an upgrade?" or something like that.

**Comment by ceripower** [comment]
> Maybe change the the wording to something "Around 36 months, ping PeopleOps, if your device needs an upgrade?" or something like that.

Done!

**Comment by ceripower** [comment]
Updated: https://people-ops.status.im/lifeatstatus/

**Comment by ceripower** [comment]
Added broadcasting to YT page

**Comment by ceripower** [comment]
Added Livepeer page, fixed broken link to https://status.im/contribute/open_positions.html

**Comment by ceripower** [comment]
Proposed fix - search functionality

**Comment by ceripower** [comment]
Updated content in `getting started`, `security` and `offboarding`

**Comment by ceripower** [comment]
- Added missing links in [recommended reading](https://people-ops.status.im/essential-reading/)
- Updated People Ops service [page](https://people-ops.status.im/your-partner/)

**Comment by ceripower** [comment]
@rajanie  what's happening with this draft page?: https://people-ops-status.ghost.io/ghost/#/editor/5c4189a28bcd7700c01cfed7

**Comment by ceripower** [comment]
Probably not super relevant anymore, but updated outdated references in [Dogfooding](https://people-ops.status.im/dogfooding/) guide.

**Comment by ceripower** [comment]
Removed Slack kudos page

**Comment by ceripower** [comment]
@jonathanbarker is the [referral bonus](https://people-ops.status.im/refer-a-friend/) scheme still active?

**Comment by ceripower** [comment]
Deleted `Glossary` page - wasn't adding anything useful that couldn't be found elsewhere

**Comment by jonathanbarker** [comment]
No - I would say we archive the referral bonus given our lack of hiring (and new approach to onboarding contribution).

**Comment by rajanie** [comment]
made some updates: 
- people-ops.status.im/travel-for-status/

Out of curiosity, how do we feel about the travel meal allowance, _$75 per day (trip average) for meals._ Is that too high?

**Comment by rajanie** [comment]
updated the events page: https://people-ops-status.ghost.io/ghost/#/editor/5c4189a28bcd7700c01cfed7
How does this look?

**Comment by ceripower** [comment]
> How does this look?

DMed you!

**Comment by ceripower** [comment]
> Out of curiosity, how do we feel about the travel meal allowance, _$75 per day (trip average) for meals._ Is that too high?

I think that's reasonable for three meals 👍

**Comment by rajanie** [comment]
Events page updated: https://people-ops.status.im/p/4b40202a-abb4-4c5f-8e85-08bb065c6142/

**Comment by ceripower** [comment]
> Events page updated: https://people-ops.status.im/p/4b40202a-abb4-4c5f-8e85-08bb065c6142/
> 
> > <img alt="" width="48" src="/favicon.png">People Ops at Status**[Events](https://people-ops.status.im/p/4b40202a-abb4-4c5f-8e85-08bb065c6142/)**Would you like to attend an event or attend a conference or have a team offsite? Join the Status group #statusevents for all the latest updates!Not sure where to start for getting budget and attendance approval, follow these steps: Team Budgets  Each team has their own budget. You need

Looks good @rajanie!

**Comment by ceripower** [comment]
Closing this as all pages are up to date. We'll need a new task to track the migration of the content into the new website once it's ready, but for now the Q1 work of updating our docs is done.
