### ISSUE TITLE
O2KR6 - More 1:1s with team leads / contributors

### ISSUE THREAD

**Issue by jonathanbarker** [status-im/people-ops#22]
PeopleOps 1:1s with contributors.

**Comment by ceripower** [comment]
My 2cents - I think we should aim for a cadence of minimum annually for all contributors, and quarterly for team leads. 

Wdyt @jonathanbarker and @rajanie? If this sounds ok to you all, I can create a schedule to stagger them throughout the coming months, along with a plan.

Broadly speaking the idea is just to have a regular touchpoint with someone outside of your team to check in on how things are going, troubleshoot any pain points, and provide proactive support.

Feedback from 1:1s will be shared with Carl/Nabil/Jarrad/People Ops with the objective of helping everyone better get a pulse on org health, and not duplicating efforts with multiple people checking in with the same contributor. 1:1s can be confidential/off-record too if someone prefers that.

When setting up 1:1s, we can make a doc which outlines what 1:1s are for and how we use the info, so people are informed and know what the 1:1 is about.

**Comment by rajanie** [comment]
I think it's a great idea. I can help create the plan and schedule. 

I would love to shadow you and/or JB for the first couple of rounds to get a better understanding of how to lead discussions like this and get feedback for contributors.

**Comment by ceripower** [comment]
@Awesome - we have our monthly hangout next week, so we can use that to make a plan?

**Comment by ceripower** [comment]
Awesome! @rajanie we have our monthly hangout next week, we can use that to make a plan :)

**Comment by ceripower** [comment]
Draft doc explaining what 1:1s are, FYR: https://people-ops-status.ghost.io/ghost/#/editor/post/5c9350192b81ef00c0c29a48

**Comment by jonathanbarker** [comment]
Moved to Wrike
