### ISSUE TITLE
O4KR2 - Privacy and storage of sensitive people/finance docs/data

### ISSUE THREAD

**Issue by jonathanbarker** [status-im/people-ops#25]
Ongoing update/audit.

**Comment by ceripower** [comment]
Did a detailed sweep of Google Drive today and migrated (sensitive) People Ops content into the one central folder under `Status Contracts` > `People Ops`.

@jonathanbarker I added some folders into the `Recruiting` [folder](https://drive.google.com/drive/u/0/folders/1tWbe1egaOPeeOg8bxG2iRTHG02B8QmoN) for migrated content relating to hiring. It's likely no longer relevant and can be trashed, but wanted to share with you in case useful.

**Comment by jonathanbarker** [comment]
Thanks @ceripower I think it's unlikely (but not impossible) we'll need a lot of the information again but it doesn't hurt to keep it around if we have the available storage space.
