### ISSUE TITLE
O5KR1 - Document internal processes across People Ops

### ISSUE THREAD

**Issue by jonathanbarker** [status-im/people-ops#28]

**Comment by ceripower** [comment]
Made a folder [here](https://drive.google.com/drive/u/0/folders/1ks21-hcoXNUkaFi0VwvMJInQllOhQU8y) for us to add our process docs too. We can work on drafts here in the meantime and put them somewhere public later if there's nothing in there that's sensitive (I doubt it).

**Comment by ceripower** [comment]
Making a list of the docs/processes we want to get written down, please add any you'd like to see:

- Onboarding
- Access to tools - BambooHR/ Expensify/ Google - what are our policies and rationale for when to open accounts for different contributor types
- Offboarding
- Drafting contracts
- Payroll changes
- Approval flows / points of contact / who to involve and when
- Hiring?
- Record keeping
- Maintenance of BambooHR
- Data protection
- Expense approval and reimbursement
- Supporting team leads

**Comment by rajanie** [comment]
Should we assign owners to each task to document?

**Comment by ceripower** [comment]
> Should we assign owners to each task to document?

Sure thing - I changed the list above into a checklist, so feel free to grab whichever ones you want to work on (or assign people) 👍

**Comment by ceripower** [comment]
Here's the first draft of [Access to Tools](https://docs.google.com/document/d/1GJ-rNV3-EiMNLIJp5PLD2W3MlpKN-jR5iZMUaQGzeo4/edit#) FYR

**Comment by jonathanbarker** [comment]
Draft of [hiring](https://docs.google.com/document/d/1lKZO5JxfMREnZQ8j3SL4yL7fxDHAdEeSREL-6BkULpA/edit).

Note: likely to evolve if we do hire in 2019.

**Comment by ceripower** [comment]
- [Drafting contracts](https://docs.google.com/document/d/1mzeZYeQX9645lEy9D4OHwr4KTiwiPmAnwWy_PGluB1k/edit#)

**Comment by ceripower** [comment]
[Payroll changes](https://docs.google.com/document/d/11yAR10hQv8QSFzozdeTn40dpvbpwJMVigTL1p5srtuY/edit#)

**Comment by ceripower** [comment]
[Approval flows / contacts](https://docs.google.com/document/d/1pQWbXH12bi4SIxDClWhTiYT96J7eDmCO-u3szjDCgZg/edit#)

**Comment by ceripower** [comment]
[SNT payouts](https://docs.google.com/document/d/1Ps2sTVnl3iIrbiUs74Hw32idoxSO39fDs16uBxz-Y2w/edit#)

**Comment by rajanie** [comment]
[off-boarding](https://docs.google.com/document/d/1zYz-rDy1vpnz5AqMs5FhxbsnEGHfze4AqfaszzQILBw/edit)

**Comment by rajanie** [comment]
Expense approval and reimbursement - starting to work on

**Comment by ceripower** [comment]
I'll grab record keeping

**Comment by ceripower** [comment]
[Record keeping/data privacy](https://docs.google.com/document/d/1SLCzE9Mn-HfY3fNiK7Fk2rNXiPfABS5ZX8yiAM1Ri0g/edit#)

**Comment by ceripower** [comment]
[Maintenance of BambooHR](https://docs.google.com/document/d/1oawbhoJlgqVqRYEMsAP__8UJA9PRIRmxc5xz5lVlHVE/edit#)

**Comment by ceripower** [comment]
Adding a note that we should make a Comp Philosophy/Principles doc (as per our discussion today), wdyt @rajanie @jonathanbarker ?

**Comment by jonathanbarker** [comment]
Yep, I think it would be good to have some benchmark  figures (using existing contributor pay) that we can apply for any new hires we bring on - led also by our "comp philosophy". 
(But given we're not hiring right now, it's not urgent).

**Comment by ceripower** [comment]
Closing this issue as all the documentation was created
