### ISSUE TITLE
O4KR1 - review any BambooHR fields not being used that contain sensitive data, e.g. ethnicity, and purge all data

### ISSUE THREAD

**Issue by jonathanbarker** [status-im/people-ops#29]

**Comment by jonathanbarker** [comment]
@ceripower I think you mentioned this OKR is complete?

**Comment by ceripower** [comment]
Emptied all data in FLSA, EEO1  & Ethnicity fields (these are US-centric fields and we don't have a reporting obligation related to this type of data).

https://statusim.bamboohr.com/reports/custom/Sensitive+data+review/167?

**Comment by ceripower** [comment]
Updated the [onboarding checklist](https://statusim.bamboohr.com/settings/tasklists/edit.php?type=onboarding) to mention for new joiners that we only need basic personal info.
