### ISSUE TITLE
Engagement survey

### ISSUE THREAD

**Issue by jonathanbarker** [status-im/people-ops#35]
Update and rerun the engagement survey that was sent out in 2018.

**Comment by rajanie** [comment]
draft in google form: https://docs.google.com/forms/d/1srYM3XaoZ7LSc-pS1gpUEGYU6OzC8U8_0Jt10N3st_E/prefill

**Comment by ceripower** [comment]
I tried to look back and find the intro text for how we teed up this survey last time. I don't have the "cover letter" (as it was added in Polly and the survey's now been deleted along with our account membership). I did find the following links talking about contributor experience and how we want to learn more with a view to improving it:

- https://our.status.im/contributor-experience/
- https://discuss.status.im/t/contributor-experience-what-changes-would-you-like-to-see-at-status/266

I think we could help people contextualise this survey by adding some background

- Why are we doing this survey? Why now?
- When was the last survey?
- What do we hope to get out of this?
- What are the deadlines/ when will people see the results?
- What's the time commitment?
- Is the survey anonymous?
- Who to contact for help/with questions?

Could also think about a comms plan, maybe a Discuss post addressing ^, and can link the Discuss post in the top of the Google survey so anyone receiving the link from fresh can navigate to more info if they need it prior to completing it.

On the question set, couple of thoughts (mainly open questions as food for thought.):

- Should all questions be mandatory, or are we happy if people skip ones they don't feel they have enough context to answer?
- The first and last two questions could all be Likert scale questions, with a lead question, e.g.

>Please rate how you feel about:
>- The quality of leadership at Status
>- Overall team morale
>- The direction Status is heading ... etc.

- Maybe we could run the question set by a few diverse people from across the org to get their thoughts on what would be useful to capture, does this question set represent the things that are a) most critical to Status and its objectives, and b) we're most curious to know about
- Is this more of a pulse than engagement survey? Will having the answers to this question set help us determine if people are engaged, or something else? Consider re-naming the survey if appropriate
- Hester from UX probably has a bunch of useful knowledge about surveys, not sure about her capacity but could be interesting to run it by her for her thoughts about how the questions are laid out.

Cheers and let me know how I can help!

**Comment by rajanie** [comment]
@ceripower reviewed your notes. we can come up with a comms plan and send it out after the townhall?

**Comment by rajanie** [comment]
i think we can run the questions by Jb and nabil, but if we ask too many people about what type of questions we're asking, it might ever get sent out - I think it's good to keep it as a PeopleOps survey and refine the questions we have, if needed.

**Comment by ceripower** [comment]
@rajanie 

> @ceripower reviewed your notes. we can come up with a comms plan and send it out after the townhall?

Sounds good! Let me know if you wanted me to spin it up, or if you wanted to have a call.

> i think we can run the questions by Jb and nabil, but if we ask too many people about what type of questions we're asking, it might ever get sent out - I think it's good to keep it as a PeopleOps survey and refine the questions we have, if needed.
Cool, makes sense - I take your point :D

**Comment by rajanie** [comment]
@ceripower ill send out the deck tomorrow and lets have a chat about everything. ill schedule some time :)

**Comment by ceripower** [comment]
Plan is to launch at 18th Feb TH

**Comment by jonathanbarker** [comment]
Nice job @ceripower & @rajanie on the Engagement Survey - lots of useful data. Closing this issue as it's completed, and will create a new issue for a follow-up survey in Q2 per the discussion this week.
