### ISSUE TITLE
[Operational excellence] Eliminate single points of failure in the organisation

### ISSUE THREAD

**Issue by jonathanbarker** [status-im/people-ops#49]
Audit current access to systems/tools/accounts and eliminate single points of ownership or access.

**Comment by ceripower** [comment]
Things to consider:

- Succession plans
- Backups and cover for AFK
- Documenting processes

**Comment by jonathanbarker** [comment]
Need to audit this list to help determine this OKR: https://docs.google.com/spreadsheets/d/1ytUDqlg288_qQKWF6t2u00G9V5zcxXmXS1YThp9_R9s/edit#gid=0

**Comment by jonathanbarker** [comment]
Moved to Wrike
