### ISSUE TITLE
[Organisation development & Support the Community] Launch Meritocracy dapp

### ISSUE THREAD

**Issue by jonathanbarker** [status-im/people-ops#50]

**Comment by ceripower** [comment]
Swarm page: https://notes.status.im/mcrnBL31Tl-KPWorAgIqbA?both

Ideas about success metrics:

> Review quarterly to review success of DApp:
> 
> - Engagement - > 50% of core contributors (currently = 32 people) using the DApp regularly (at least once a month)
> - Functionality - all open issues closed and volume of problems reported reduced
> - Feedback - anecdotal feedback from users positive, do CCs enjoy and benefit from using the DApp?
> - Utility - does the data generated through the DApp accurately represent a Meritocracy, or are there any concerns/issues.

**Comment by jonathanbarker** [comment]
Moved to Wrike
