### ISSUE TITLE
[Organisational development] Compile and maintain roadmap

### ISSUE THREAD

**Issue by ceripower** [status-im/people-ops#56]
https://discuss.status.im/t/combined-roadmap-timeline-of-efforts/1088

**Comment by ceripower** [comment]
@jonathanbarker not sure if this is still something we want to work on, but adding it here as the proposal looked open still in Discuss.

I think alongside higher level org objectives, it could be helpful to define how we see the Status org (makeup, contributor numbers) change (or not) with each phase.

**Comment by jonathanbarker** [comment]
Thanks @ceripower yes think this still makes sense. I'm trying out something Jarrad's been working with which I think could fill the roadmap/direction void. Will update here!

**Comment by jonathanbarker** [comment]
Moved To Wrike
