### ISSUE TITLE
[Support the community] Countdown to November - comms

### ISSUE THREAD

**Issue by ceripower** [status-im/people-ops#61]
Start this in June - as we get closer to the end of our runway, we should think about a proactive comms plan to articulate the next steps and possible scenarios for the project.

This will give everyone enough lead time to look for other opportunities (if November really is the end of the road) or anticipate any future redundancies (if it gets to that point). Alternatively, maybe the financial situation is looking better and we can formally extend the runway.

We should make this process as consultative as possible so people feel bought in and part of the change.

**Comment by jonathanbarker** [comment]
Good idea. I think it's more of a rolling process (both the runway, and communications). But agree we should provide timely updates to everyone.

**Comment by jonathanbarker** [comment]
Moved to Wrike
