### ISSUE TITLE
[Grow the community] Blog posts highlighting contributor activities

### ISSUE THREAD

**Issue by ceripower** [status-im/people-ops#63]
This was something that was done a while back, wdyt to refreshing it?

**Comment by ceripower** [comment]
Asked Jonny/Rajanie about this and it seems beyond Twitter announcements for new CCs, we didn't do anything for recognising contributors. Jonny said:

> I think we can do more for the community contributors in all honesty. I think we should put together a welcome package for the people who really get involved 

Personally, I think this is a cool idea - maybe like a postcard with a handwritten note and/or some swag?

**Comment by jonathanbarker** [comment]
Moved to Wrike
