### ISSUE TITLE
[Operational excellence] PeopleOps: Everyone creates a developmental plan for their wants for development this quarter

### ISSUE THREAD

**Issue by ceripower** [status-im/people-ops#64]

**Comment by ceripower** [comment]
Activities to feed into this - feedback round (inc legal and finance, if they want to take part).

Also have an idea about a session we can do about inventorying how well we know others within the team, which we can use to help each other find good developmental opportunities. Not a prio at all but something we can try for a bit of fun for professional development time if we get a chance.

**Comment by jonathanbarker** [comment]
Moved to Wrike
