### ISSUE TITLE
[Support the community] Health & wellness focus

### ISSUE THREAD

**Issue by ceripower** [status-im/people-ops#65]
Adding this one more to bounce the idea. Was thinking based on the last engagement survey and some of the responses around stress and anxiety, that it could be useful to do some kind of initiative around health and wellness, e.g. - Surveying contributors to get a picture of work/life balance, sharing best practices, talking about mental health days, fitness challenges etc. Not really a fully formed thought, yet - sorry! Interested to hear your thoughts on this kind of topic

**Comment by rajanie** [comment]
I think this is a really great idea and would love to help out.

**Comment by jonathanbarker** [comment]
Moved to Wrike
